name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{  secrets.GKE_PROJECT  }}
  GKE_CLUSTER: deployment-demo
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: github-deployment
  IMAGE: github-actions-image
  TAG: 1.0.0
  SERVICE: webapp  # Add a service name here

jobs:
  build:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      

      - name: Build with Maven
        run: mvn clean package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Sets up the gcloud cli with the credentials we previously created, and will be storing within Github as secrets.
      - name: Setup Cloud cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true
      # Configure Docker with Credentials
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/deployment-github-424417/${{ env.SERVICE }}:${{ github.sha }} .
      
      - name: Push Docker image to Container Registry
        run: docker push gcr.io/deployment-github-424417/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.gohibeesh.outputs.url }}

      - name: Deploy to Cloud Run
        id: gohibeesh
        run: gcloud run deploy ${{env.SERVICE}} --image gcr.io/deployment-github-424417/${{ env.SERVICE }}:${{  github.sha }} --region ${{env.REGION}} --cpu=1 --memory=1Gi --timeout=3000 --allow-unauthenticated || true

        


